### ISSUE TITLE
How to use doxygen?

### ISSUE THREAD

**Issue by tienll** [swiftlang/swift-markdown#192]
Hi guys, I happened to find that the doxygen has been supported, however it doesn't work for me.

Can I expect the same thing like [doxygen notes](https://github.com/doxygen/doxygen/issues/10608) ? Or can you share some snippets to show how can I use doxygen with this lib?

Thanks!

**Comment by QuietMisdreavus** [comment]
Swift-Markdown supports a very limited set of Doxygen commands, specifically just `\discussion`, `\note`, `\param`, and `\returns`. To parse them from the library API, pass `.parseBlockDirectives` and `.parseMinimalDoxygen` for the `options` parameters in `Document.init(parsing:source:options:)` or `Document.init(parsing:options:)`.

**Comment by tienll** [comment]
Thank you, it works!
