### ISSUE TITLE
Export parsed document as html

### ISSUE THREAD

**Issue by mynona** [swiftlang/swift-markdown#193]
How can I export the parsed document as HTML string?

**Comment by MahdiBM** [comment]
I'd expect that you'd need to write a `MarkupVisitor` that transforms the markdown into HTML.
The question is, would swift-markdown want to host such a visitor and provide it by default?
Based on my experience, this wouldn't be a niche feature.

I know Vapor-Community's HTMLKit [does have such a feature](https://github.com/vapor-community/HTMLKit/tree/a142bc5f05e184bd5e5f29e68c460a7d77ebe2b7/Sources/HTMLKit/Framework/Rendering/Markdown) already, although I haven't used it myself.

**Comment by mynona** [comment]
Hi @MahdiBM , ok, I get it, this repository is just to parse markdown to Swift. It's a pitty because we have already three repositories basically doing the same

1. This one (because cmark provides already a function for this)
2. Vapor community: The wrapper from Tim -> filled a issue for this one 
3. Vapor community: HTMLKit

Maybe it would be good to have one repository to handle this. Just a thought.

Anyway, thanks for your answer.

**Comment by MahdiBM** [comment]
I'm on the same page as you. It might be worth it to have markdown to HTML conversions here.
I'd be curious to know what @QuietMisdreavus thinks.

**Comment by 0xTim** [comment]
There's also https://github.com/twostraws/Ignite/blob/f14274e7b265db6037396d0cf8d6376b78bb00be/Sources/Ignite/Rendering/Markdown/MarkdownToHTML.swift

**Comment by QuietMisdreavus** [comment]
Revisiting this thread: I've just merged https://github.com/swiftlang/swift-markdown/pull/106, so if you can use the `main` branch in your projects you should be able to use this functionality in Swift-Markdown.
