### ISSUE TITLE
HTMLFormatter Dependency issue

### ISSUE THREAD

**Issue by mynona** [swiftlang/swift-markdown#199]
Unfortunately, the great enhancement by @QuietMisdreavus  has just been merged to "main" but not released.

When I use this feature in a library with SPM:

```
.package(url: "https://github.com/swiftlang/swift-markdown.git", revision: "2c126ce9fa33fc8b48258ee27ab51b33989161a3"),
```

(Regardless if I use revision to point to the commit or branch)

and import it as dependency to another project then SPM fails with the following error message as it doesn't accept branch or revision as a stable version.

```
Package XY cannot be used because package XY is required using a stable-version but XY depends on an unstable-version package 'swift-markdown' 
```

@QuietMisdreavus 
Could you please be so kind and release this enhancement with a release version number?

Or in case, there is a work-around for SPM maybe you can support me how to reference to the commit or branch as dependency. The issue only appears when pointing to another package that has the dependency (2 level). If you import it directly to one feature it works with revision and branch. Unfortunately, SPM, will also not accept revision or branch if you try to import it in all features.

Additionally I found a small bug: added it here as it is related to the newline issue
https://github.com/swiftlang/swift-markdown/issues/197

**Comment by MahdiBM** [comment]
@mynona have you tried forking this repo and depending on the fork instead?
SwiftPM will still complain (warning, not error), but at least you might get unblocked for now.

**Comment by mynona** [comment]
Hi @MahdiBM , yes this will be the work-around (thx) but let's first see if a release is possible. That would actually be the proper way.

**Comment by QuietMisdreavus** [comment]
Thank you for testing the HTML Formatter!

Swift-Markdown releases version tags based on releases of Swift itself. When a major or minor release of Swift is finalized, we tag the corresponding `release/*.*` branch in Swift-Markdown with a new version and push it up. This means that the code that currently lives in main (like `HTMLFormatter`) will only be part of a tagged release once the next version of Swift after 6.0 is released.

If you want to test the HTML Formatter before that happens, you need to depend on branch or commit versions for the entire dependency line that leads to Swift-Markdown. You cannot depend on a tagged version that itself depends on a branch or commit; that is part of the entire design of Swift Package Manager.

**Comment by mynona** [comment]
I guess 6.0 will anyway be released soon and this problem will be solved :-)

**Comment by QuietMisdreavus** [comment]
6.0 will not have this change, as the formatter was not cherry-picked into `release/6.0`. The release *after* 6.0 will have this change.

**Comment by 0xTim** [comment]
Related - https://github.com/swiftlang/swift-markdown/issues/178
